name: Deploy Now

on: [push]

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 52f12f5b-5cfb-4c78-b173-0580d6f99dc9
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Node.js 14.x
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Prepare project environment
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm install
      - name: Build project
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: npm run generate
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: dist
          project: 52f12f5b-5cfb-4c78-b173-0580d6f99dc9
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          branch-id: ${{ steps.project.outputs.branch-id }}
